//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhiFanmade.Tool.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhiFanmade.Tool.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhiFanmade 开源工具集.
        /// </summary>
        public static string cli_app_title {
            get {
                return ResourceManager.GetString("cli_app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPE 谱面操作.
        /// </summary>
        public static string cli_branch_rpe_desc {
            get {
                return ResourceManager.GetString("cli_branch_rpe_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区管理.
        /// </summary>
        public static string cli_branch_workspace_desc {
            get {
                return ResourceManager.GetString("cli_branch_workspace_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入谱面文件到工作区，供后续操作使用.
        /// </summary>
        public static string cli_cmd_load_desc {
            get {
                return ResourceManager.GetString("cli_cmd_load_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将 RPE 谱面转换为其他格式（尚未完整实现）.
        /// </summary>
        public static string cli_cmd_rpe_convert_desc {
            get {
                return ResourceManager.GetString("cli_cmd_rpe_convert_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将所有判定线的多个事件层级合并为单一层级.
        /// </summary>
        public static string cli_cmd_rpe_layer_merge_desc {
            get {
                return ResourceManager.GetString("cli_cmd_rpe_layer_merge_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将判定线与父级解绑.
        /// </summary>
        public static string cli_cmd_rpe_unbind_father_desc {
            get {
                return ResourceManager.GetString("cli_cmd_rpe_unbind_father_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将工作区中的谱面保存到文件.
        /// </summary>
        public static string cli_cmd_save_desc {
            get {
                return ResourceManager.GetString("cli_cmd_save_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示当前版本号.
        /// </summary>
        public static string cli_cmd_version_desc {
            get {
                return ResourceManager.GetString("cli_cmd_version_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理工作区缓存（可指定 --id 只清理单个）.
        /// </summary>
        public static string cli_cmd_workspace_clear_desc {
            get {
                return ResourceManager.GetString("cli_cmd_workspace_clear_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列出所有工作区 ID.
        /// </summary>
        public static string cli_cmd_workspace_list_desc {
            get {
                return ResourceManager.GetString("cli_cmd_workspace_list_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要提供 --input 哟，或者用 --workspace 也可以~.
        /// </summary>
        public static string cli_err_input_required {
            get {
                return ResourceManager.GetString("cli_err_input_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出的结果可能有些大哦~请试着添加“--stream”选项来减少内存占用！若这没有解决你的问题，请将以下信息发送到https://github.com/NuanRMxi-Lazy-Team/PhiFanmadeTool/issues，我们会尽快修复这个问题！
        ///{0}.
        /// </summary>
        public static string cli_err_out_of_memory {
            get {
                return ResourceManager.GetString("cli_err_out_of_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要提供 --output 才能帮你保存呢~.
        /// </summary>
        public static string cli_err_output_required {
            get {
                return ResourceManager.GetString("cli_err_output_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すみません！软件遇到了未知错误！请将以下信息发送到https://github.com/NuanRMxi-Lazy-Team/PhiFanmadeTool/issues 我们会尽快修复这个问题！
        ///{0}.
        /// </summary>
        public static string cli_err_ukerr {
            get {
                return ResourceManager.GetString("cli_err_ukerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个命令功能还未完全实现呢....
        /// </summary>
        public static string cli_err_unimplemented {
            get {
                return ResourceManager.GetString("cli_err_unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咦？这条指令我还不认识呢！.
        /// </summary>
        public static string cli_err_unknown {
            get {
                return ResourceManager.GetString("cli_err_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到工作区 {0} 喵....
        /// </summary>
        public static string cli_err_workspace_missing {
            get {
                return ResourceManager.GetString("cli_err_workspace_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以用 --help 查看所有可用命令哦，或者看看 README 喵~.
        /// </summary>
        public static string cli_hint_use_help {
            get {
                return ResourceManager.GetString("cli_hint_use_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 哗啦啦~ 所有工作区都打扫干净了喵！.
        /// </summary>
        public static string cli_msg_cleared {
            get {
                return ResourceManager.GetString("cli_msg_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没想好怎么写喵...所以详见README.md喵....
        /// </summary>
        public static string cli_msg_help {
            get {
                return ResourceManager.GetString("cli_msg_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经将文件送入 {0} 工作区啦！.
        /// </summary>
        public static string cli_msg_loaded {
            get {
                return ResourceManager.GetString("cli_msg_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 做好啦！把工作区 &apos;{0}&apos; 存到 &apos;{1}&apos; 了！.
        /// </summary>
        public static string cli_msg_saved {
            get {
                return ResourceManager.GetString("cli_msg_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件已经成功输出到 {0} 了！.
        /// </summary>
        public static string cli_msg_written {
            get {
                return ResourceManager.GetString("cli_msg_written", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试运行模式，不写入文件.
        /// </summary>
        public static string cli_opt_dry_run_desc {
            get {
                return ResourceManager.GetString("cli_opt_dry_run_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的 RPE/PhiEdit 谱面文件路径.
        /// </summary>
        public static string cli_opt_input_phiedit_desc {
            get {
                return ResourceManager.GetString("cli_opt_input_phiedit_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的 RPE 谱面文件路径（与 --workspace 二选一）.
        /// </summary>
        public static string cli_opt_input_rpe_desc {
            get {
                return ResourceManager.GetString("cli_opt_input_rpe_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件路径（不填则自动生成 _PFC.json 后缀）.
        /// </summary>
        public static string cli_opt_output_auto_desc {
            get {
                return ResourceManager.GetString("cli_opt_output_auto_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件路径.
        /// </summary>
        public static string cli_opt_output_path_desc {
            get {
                return ResourceManager.GetString("cli_opt_output_path_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采样精度（每拍细分数，默认：64，即每次采样步进六十四分之一拍）.
        /// </summary>
        public static string cli_opt_precision_desc {
            get {
                return ResourceManager.GetString("cli_opt_precision_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式输出模式（若发生内存不足错误，请考虑使用此选项）.
        /// </summary>
        public static string cli_opt_stream_output_desc {
            get {
                return ResourceManager.GetString("cli_opt_stream_output_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拟合容差百分比（默认：5）.
        /// </summary>
        public static string cli_opt_tolerance_desc {
            get {
                return ResourceManager.GetString("cli_opt_tolerance_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只清理指定工作区（不填则清理全部）.
        /// </summary>
        public static string cli_opt_workspace_clear_id_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_clear_id_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID（默认：default）.
        /// </summary>
        public static string cli_opt_workspace_default_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_default_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID（与 --input 二选一）.
        /// </summary>
        public static string cli_opt_workspace_rpe_desc {
            get {
                return ResourceManager.GetString("cli_opt_workspace_rpe_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPE 转换还在化妆中，稍等一下下~.
        /// </summary>
        public static string cli_warn_rpe_convert {
            get {
                return ResourceManager.GetString("cli_warn_rpe_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开源工具集.
        /// </summary>
        public static string gui_app_subtitle {
            get {
                return ResourceManager.GetString("gui_app_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string gui_btn_browse {
            get {
                return ResourceManager.GetString("gui_btn_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string gui_btn_cancel {
            get {
                return ResourceManager.GetString("gui_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理.
        /// </summary>
        public static string gui_btn_clear {
            get {
                return ResourceManager.GetString("gui_btn_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string gui_btn_clear_log {
            get {
                return ResourceManager.GetString("gui_btn_clear_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入谱面.
        /// </summary>
        public static string gui_btn_load_chart {
            get {
                return ResourceManager.GetString("gui_btn_load_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入到工作区.
        /// </summary>
        public static string gui_btn_load_to_workspace {
            get {
                return ResourceManager.GetString("gui_btn_load_to_workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string gui_btn_refresh {
            get {
                return ResourceManager.GetString("gui_btn_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存到文件.
        /// </summary>
        public static string gui_btn_save_to_file {
            get {
                return ResourceManager.GetString("gui_btn_save_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始合并.
        /// </summary>
        public static string gui_btn_start_merge {
            get {
                return ResourceManager.GetString("gui_btn_start_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始解绑.
        /// </summary>
        public static string gui_btn_start_unbind {
            get {
                return ResourceManager.GetString("gui_btn_start_unbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试运行（不写入文件）.
        /// </summary>
        public static string gui_check_dry_run {
            get {
                return ResourceManager.GetString("gui_check_dry_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流式输出（减少内存占用）.
        /// </summary>
        public static string gui_check_stream_output {
            get {
                return ResourceManager.GetString("gui_check_stream_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先在「导入谱面」页面载入谱面.
        /// </summary>
        public static string gui_hint_nav_locked {
            get {
                return ResourceManager.GetString("gui_hint_nav_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面文件.
        /// </summary>
        public static string gui_label_chart_file {
            get {
                return ResourceManager.GetString("gui_label_chart_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理 ID.
        /// </summary>
        public static string gui_label_clear_id {
            get {
                return ResourceManager.GetString("gui_label_clear_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件路径.
        /// </summary>
        public static string gui_label_file_path {
            get {
                return ResourceManager.GetString("gui_label_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出路径.
        /// </summary>
        public static string gui_label_output_path {
            get {
                return ResourceManager.GetString("gui_label_output_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采样精度.
        /// </summary>
        public static string gui_label_precision {
            get {
                return ResourceManager.GetString("gui_label_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 容差 %.
        /// </summary>
        public static string gui_label_tolerance {
            get {
                return ResourceManager.GetString("gui_label_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区 ID.
        /// </summary>
        public static string gui_label_workspace_id {
            get {
                return ResourceManager.GetString("gui_label_workspace_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPE 层级合并.
        /// </summary>
        public static string gui_nav_rpe_layer_merge {
            get {
                return ResourceManager.GetString("gui_nav_rpe_layer_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPE 解绑父级.
        /// </summary>
        public static string gui_nav_rpe_unbind_father {
            get {
                return ResourceManager.GetString("gui_nav_rpe_unbind_father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区管理.
        /// </summary>
        public static string gui_nav_workspace {
            get {
                return ResourceManager.GetString("gui_nav_workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将判定线的所有事件层级合并为单一层级.
        /// </summary>
        public static string gui_page_merge_subtitle {
            get {
                return ResourceManager.GetString("gui_page_merge_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入谱面.
        /// </summary>
        public static string gui_page_start {
            get {
                return ResourceManager.GetString("gui_page_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先导入一份谱面文件，然后才能使用其他功能.
        /// </summary>
        public static string gui_page_start_subtitle {
            get {
                return ResourceManager.GetString("gui_page_start_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将判定线与其父级解绑，并保持运动行为不变.
        /// </summary>
        public static string gui_page_unbind_subtitle {
            get {
                return ResourceManager.GetString("gui_page_unbind_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入、保存和管理 RPE 谱面工作区.
        /// </summary>
        public static string gui_page_workspace_subtitle {
            get {
                return ResourceManager.GetString("gui_page_workspace_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入来源.
        /// </summary>
        public static string gui_section_input_source {
            get {
                return ResourceManager.GetString("gui_section_input_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入谱面.
        /// </summary>
        public static string gui_section_load_chart {
            get {
                return ResourceManager.GetString("gui_section_load_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作日志.
        /// </summary>
        public static string gui_section_op_log {
            get {
                return ResourceManager.GetString("gui_section_op_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        public static string gui_section_output {
            get {
                return ResourceManager.GetString("gui_section_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数.
        /// </summary>
        public static string gui_section_params {
            get {
                return ResourceManager.GetString("gui_section_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行日志.
        /// </summary>
        public static string gui_section_run_log {
            get {
                return ResourceManager.GetString("gui_section_run_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存工作区.
        /// </summary>
        public static string gui_section_save_workspace {
            get {
                return ResourceManager.GetString("gui_section_save_workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作区列表.
        /// </summary>
        public static string gui_section_workspace_list {
            get {
                return ResourceManager.GetString("gui_section_workspace_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载失败：{0}.
        /// </summary>
        public static string gui_status_load_error {
            get {
                return ResourceManager.GetString("gui_status_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 谱面加载成功！现在可以使用其他功能了。.
        /// </summary>
        public static string gui_status_load_success {
            get {
                return ResourceManager.GetString("gui_status_load_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在加载….
        /// </summary>
        public static string gui_status_loading {
            get {
                return ResourceManager.GetString("gui_status_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 就绪.
        /// </summary>
        public static string gui_status_ready {
            get {
                return ResourceManager.GetString("gui_status_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每拍细分数，默认 64（每步进 1/64 拍）.
        /// </summary>
        public static string gui_tooltip_precision {
            get {
                return ResourceManager.GetString("gui_tooltip_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拟合容差百分比，默认 5.
        /// </summary>
        public static string gui_tooltip_tolerance {
            get {
                return ResourceManager.GetString("gui_tooltip_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.1.x — GUI 版.
        /// </summary>
        public static string gui_version_label {
            get {
                return ResourceManager.GetString("gui_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留空则清理全部.
        /// </summary>
        public static string gui_watermark_clear_all {
            get {
                return ResourceManager.GetString("gui_watermark_clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留空则从工作区读取.
        /// </summary>
        public static string gui_watermark_input_from_workspace {
            get {
                return ResourceManager.GetString("gui_watermark_input_from_workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留空则自动生成 _PFC.json 后缀.
        /// </summary>
        public static string gui_watermark_output_auto {
            get {
                return ResourceManager.GetString("gui_watermark_output_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 RPE 谱面 JSON 文件.
        /// </summary>
        public static string gui_watermark_select_json {
            get {
                return ResourceManager.GetString("gui_watermark_select_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择输出文件位置.
        /// </summary>
        public static string gui_watermark_select_output {
            get {
                return ResourceManager.GetString("gui_watermark_select_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string gui_watermark_workspace_default {
            get {
                return ResourceManager.GetString("gui_watermark_workspace_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （与文件路径二选一）.
        /// </summary>
        public static string gui_watermark_workspace_or_file {
            get {
                return ResourceManager.GetString("gui_watermark_workspace_or_file", resourceCulture);
            }
        }
    }
}
